/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as energyDataRegistrySol from "./EnergyDataRegistry.sol";
export type { energyDataRegistrySol };
import type * as energyMarketplaceSol from "./EnergyMarketplace.sol";
export type { energyMarketplaceSol };
export type { EnergyToken } from "./EnergyToken";
export type { PriceOracle } from "./PriceOracle";
