/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  
export declare namespace PriceOracle {
      
    export type PricingScheduleStruct = {peakHourMultiplier: BigNumberish, offPeakMultiplier: BigNumberish, standardMultiplier: BigNumberish, peakStartHour: BigNumberish, peakEndHour: BigNumberish, offPeakStartHour: BigNumberish, offPeakEndHour: BigNumberish}

    export type PricingScheduleStructOutput = [peakHourMultiplier: bigint, offPeakMultiplier: bigint, standardMultiplier: bigint, peakStartHour: bigint, peakEndHour: bigint, offPeakStartHour: bigint, offPeakEndHour: bigint] & {peakHourMultiplier: bigint, offPeakMultiplier: bigint, standardMultiplier: bigint, peakStartHour: bigint, peakEndHour: bigint, offPeakStartHour: bigint, offPeakEndHour: bigint }
  
    }

  export interface PriceOracleInterface extends Interface {
    getFunction(nameOrSignature: "ADMIN_ROLE" | "DEFAULT_ADMIN_ROLE" | "PRICE_UPDATER_ROLE" | "addPriceUpdater" | "basePrice" | "calculateOptimalPrice" | "currentPrice" | "currentTotalDemand" | "currentTotalSupply" | "externalPriceFeed" | "getCurrentPrice" | "getCurrentTimeMultiplier" | "getHistoricalPrices" | "getLatestPrices" | "getMovingAveragePrice" | "getPrice" | "getRoleAdmin" | "getSupplyDemand" | "grantRole" | "hasRole" | "historicalPrices" | "isOffPeakHour" | "isPeakHour" | "lastUpdateTime" | "maxPrice" | "minPrice" | "minUpdateInterval" | "movingAveragePeriod" | "movingAveragePrice" | "pause" | "paused" | "priceTimestamps" | "pricingSchedule" | "renounceRole" | "revokeRole" | "setBasePrice" | "setExternalPriceFeed" | "setMinUpdateInterval" | "setMovingAveragePeriod" | "setPrice" | "setPriceBounds" | "setPricingSchedule" | "setUseExternalFeed" | "supplyDemandFactor" | "supportsInterface" | "unpause" | "updatePrice" | "useExternalFeed"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "BasePriceUpdated" | "MovingAverageUpdated" | "Paused" | "PriceBoundsUpdated" | "PriceUpdated" | "PriceUpdaterAdded" | "PricingScheduleUpdated" | "RoleAdminChanged" | "RoleGranted" | "RoleRevoked" | "SupplyDemandUpdated" | "Unpaused"): EventFragment;

    encodeFunctionData(functionFragment: 'ADMIN_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'DEFAULT_ADMIN_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'PRICE_UPDATER_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'addPriceUpdater', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'basePrice', values?: undefined): string;
encodeFunctionData(functionFragment: 'calculateOptimalPrice', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'currentPrice', values?: undefined): string;
encodeFunctionData(functionFragment: 'currentTotalDemand', values?: undefined): string;
encodeFunctionData(functionFragment: 'currentTotalSupply', values?: undefined): string;
encodeFunctionData(functionFragment: 'externalPriceFeed', values?: undefined): string;
encodeFunctionData(functionFragment: 'getCurrentPrice', values?: undefined): string;
encodeFunctionData(functionFragment: 'getCurrentTimeMultiplier', values?: undefined): string;
encodeFunctionData(functionFragment: 'getHistoricalPrices', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getLatestPrices', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getMovingAveragePrice', values?: undefined): string;
encodeFunctionData(functionFragment: 'getPrice', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getRoleAdmin', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'getSupplyDemand', values?: undefined): string;
encodeFunctionData(functionFragment: 'grantRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'hasRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'historicalPrices', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'isOffPeakHour', values?: undefined): string;
encodeFunctionData(functionFragment: 'isPeakHour', values?: undefined): string;
encodeFunctionData(functionFragment: 'lastUpdateTime', values?: undefined): string;
encodeFunctionData(functionFragment: 'maxPrice', values?: undefined): string;
encodeFunctionData(functionFragment: 'minPrice', values?: undefined): string;
encodeFunctionData(functionFragment: 'minUpdateInterval', values?: undefined): string;
encodeFunctionData(functionFragment: 'movingAveragePeriod', values?: undefined): string;
encodeFunctionData(functionFragment: 'movingAveragePrice', values?: undefined): string;
encodeFunctionData(functionFragment: 'pause', values?: undefined): string;
encodeFunctionData(functionFragment: 'paused', values?: undefined): string;
encodeFunctionData(functionFragment: 'priceTimestamps', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'pricingSchedule', values?: undefined): string;
encodeFunctionData(functionFragment: 'renounceRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'revokeRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'setBasePrice', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'setExternalPriceFeed', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'setMinUpdateInterval', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'setMovingAveragePeriod', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'setPrice', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'setPriceBounds', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'setPricingSchedule', values: [PriceOracle.PricingScheduleStruct]): string;
encodeFunctionData(functionFragment: 'setUseExternalFeed', values: [boolean]): string;
encodeFunctionData(functionFragment: 'supplyDemandFactor', values?: undefined): string;
encodeFunctionData(functionFragment: 'supportsInterface', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'unpause', values?: undefined): string;
encodeFunctionData(functionFragment: 'updatePrice', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'useExternalFeed', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'ADMIN_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'DEFAULT_ADMIN_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'PRICE_UPDATER_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'addPriceUpdater', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'basePrice', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'calculateOptimalPrice', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'currentPrice', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'currentTotalDemand', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'currentTotalSupply', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'externalPriceFeed', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getCurrentPrice', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getCurrentTimeMultiplier', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getHistoricalPrices', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getLatestPrices', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getMovingAveragePrice', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getPrice', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getRoleAdmin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getSupplyDemand', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'grantRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hasRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'historicalPrices', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isOffPeakHour', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isPeakHour', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'lastUpdateTime', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'maxPrice', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'minPrice', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'minUpdateInterval', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'movingAveragePeriod', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'movingAveragePrice', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pause', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'paused', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'priceTimestamps', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pricingSchedule', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'revokeRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setBasePrice', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setExternalPriceFeed', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setMinUpdateInterval', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setMovingAveragePeriod', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setPrice', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setPriceBounds', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setPricingSchedule', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setUseExternalFeed', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'supplyDemandFactor', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'supportsInterface', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'unpause', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updatePrice', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'useExternalFeed', data: BytesLike): Result;
  }

  
    export namespace BasePriceUpdatedEvent {
      export type InputTuple = [oldPrice: BigNumberish, newPrice: BigNumberish];
      export type OutputTuple = [oldPrice: bigint, newPrice: bigint];
      export interface OutputObject {oldPrice: bigint, newPrice: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace MovingAverageUpdatedEvent {
      export type InputTuple = [newAverage: BigNumberish];
      export type OutputTuple = [newAverage: bigint];
      export interface OutputObject {newAverage: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PausedEvent {
      export type InputTuple = [account: AddressLike];
      export type OutputTuple = [account: string];
      export interface OutputObject {account: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PriceBoundsUpdatedEvent {
      export type InputTuple = [minPrice: BigNumberish, maxPrice: BigNumberish];
      export type OutputTuple = [minPrice: bigint, maxPrice: bigint];
      export interface OutputObject {minPrice: bigint, maxPrice: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PriceUpdatedEvent {
      export type InputTuple = [timestamp: BigNumberish, oldPrice: BigNumberish, newPrice: BigNumberish, supply: BigNumberish, demand: BigNumberish];
      export type OutputTuple = [timestamp: bigint, oldPrice: bigint, newPrice: bigint, supply: bigint, demand: bigint];
      export interface OutputObject {timestamp: bigint, oldPrice: bigint, newPrice: bigint, supply: bigint, demand: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PriceUpdaterAddedEvent {
      export type InputTuple = [updater: AddressLike];
      export type OutputTuple = [updater: string];
      export interface OutputObject {updater: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PricingScheduleUpdatedEvent {
      export type InputTuple = [schedule: PriceOracle.PricingScheduleStruct];
      export type OutputTuple = [schedule: PriceOracle.PricingScheduleStructOutput];
      export interface OutputObject {schedule: PriceOracle.PricingScheduleStructOutput };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleAdminChangedEvent {
      export type InputTuple = [role: BytesLike, previousAdminRole: BytesLike, newAdminRole: BytesLike];
      export type OutputTuple = [role: string, previousAdminRole: string, newAdminRole: string];
      export interface OutputObject {role: string, previousAdminRole: string, newAdminRole: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleGrantedEvent {
      export type InputTuple = [role: BytesLike, account: AddressLike, sender: AddressLike];
      export type OutputTuple = [role: string, account: string, sender: string];
      export interface OutputObject {role: string, account: string, sender: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleRevokedEvent {
      export type InputTuple = [role: BytesLike, account: AddressLike, sender: AddressLike];
      export type OutputTuple = [role: string, account: string, sender: string];
      export interface OutputObject {role: string, account: string, sender: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace SupplyDemandUpdatedEvent {
      export type InputTuple = [supply: BigNumberish, demand: BigNumberish];
      export type OutputTuple = [supply: bigint, demand: bigint];
      export interface OutputObject {supply: bigint, demand: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace UnpausedEvent {
      export type InputTuple = [account: AddressLike];
      export type OutputTuple = [account: string];
      export interface OutputObject {account: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface PriceOracle extends BaseContract {
    
    connect(runner?: ContractRunner | null): PriceOracle;
    waitForDeployment(): Promise<this>;

    interface: PriceOracleInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    ADMIN_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    DEFAULT_ADMIN_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    PRICE_UPDATER_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    addPriceUpdater: TypedContractMethod<
      [updater: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    basePrice: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    calculateOptimalPrice: TypedContractMethod<
      [supply: BigNumberish, demand: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    currentPrice: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    currentTotalDemand: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    currentTotalSupply: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    externalPriceFeed: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    getCurrentPrice: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    getCurrentTimeMultiplier: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    getHistoricalPrices: TypedContractMethod<
      [fromTimestamp: BigNumberish, toTimestamp: BigNumberish, ],
      [[bigint[], bigint[]] & {timestamps: bigint[], prices: bigint[] }],
      'view'
    >
    

    
    getLatestPrices: TypedContractMethod<
      [count: BigNumberish, ],
      [[bigint[], bigint[]] & {timestamps: bigint[], prices: bigint[] }],
      'view'
    >
    

    
    getMovingAveragePrice: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    getPrice: TypedContractMethod<
      [timestamp: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    getRoleAdmin: TypedContractMethod<
      [role: BytesLike, ],
      [string],
      'view'
    >
    

    
    getSupplyDemand: TypedContractMethod<
      [],
      [[bigint, bigint] & {supply: bigint, demand: bigint }],
      'view'
    >
    

    
    grantRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    hasRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    historicalPrices: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, bigint, bigint, bigint, boolean] & {price: bigint, timestamp: bigint, totalSupply: bigint, totalDemand: bigint, exists: boolean }],
      'view'
    >
    

    
    isOffPeakHour: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    isPeakHour: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    lastUpdateTime: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    maxPrice: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    minPrice: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    minUpdateInterval: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    movingAveragePeriod: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    movingAveragePrice: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    pause: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    paused: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    priceTimestamps: TypedContractMethod<
      [arg0: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    pricingSchedule: TypedContractMethod<
      [],
      [[bigint, bigint, bigint, bigint, bigint, bigint, bigint] & {peakHourMultiplier: bigint, offPeakMultiplier: bigint, standardMultiplier: bigint, peakStartHour: bigint, peakEndHour: bigint, offPeakStartHour: bigint, offPeakEndHour: bigint }],
      'view'
    >
    

    
    renounceRole: TypedContractMethod<
      [role: BytesLike, callerConfirmation: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    revokeRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setBasePrice: TypedContractMethod<
      [newBasePrice: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setExternalPriceFeed: TypedContractMethod<
      [feedAddress: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setMinUpdateInterval: TypedContractMethod<
      [intervalInSeconds: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setMovingAveragePeriod: TypedContractMethod<
      [periodInHours: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setPrice: TypedContractMethod<
      [newPrice: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setPriceBounds: TypedContractMethod<
      [_minPrice: BigNumberish, _maxPrice: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setPricingSchedule: TypedContractMethod<
      [schedule: PriceOracle.PricingScheduleStruct, ],
      [void],
      'nonpayable'
    >
    

    
    setUseExternalFeed: TypedContractMethod<
      [_useExternal: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    supplyDemandFactor: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    supportsInterface: TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    unpause: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    updatePrice: TypedContractMethod<
      [totalSupply: BigNumberish, totalDemand: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    useExternalFeed: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'ADMIN_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'DEFAULT_ADMIN_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'PRICE_UPDATER_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'addPriceUpdater'): TypedContractMethod<
      [updater: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'basePrice'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'calculateOptimalPrice'): TypedContractMethod<
      [supply: BigNumberish, demand: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'currentPrice'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'currentTotalDemand'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'currentTotalSupply'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'externalPriceFeed'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getCurrentPrice'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getCurrentTimeMultiplier'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getHistoricalPrices'): TypedContractMethod<
      [fromTimestamp: BigNumberish, toTimestamp: BigNumberish, ],
      [[bigint[], bigint[]] & {timestamps: bigint[], prices: bigint[] }],
      'view'
    >;
getFunction(nameOrSignature: 'getLatestPrices'): TypedContractMethod<
      [count: BigNumberish, ],
      [[bigint[], bigint[]] & {timestamps: bigint[], prices: bigint[] }],
      'view'
    >;
getFunction(nameOrSignature: 'getMovingAveragePrice'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getPrice'): TypedContractMethod<
      [timestamp: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getRoleAdmin'): TypedContractMethod<
      [role: BytesLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getSupplyDemand'): TypedContractMethod<
      [],
      [[bigint, bigint] & {supply: bigint, demand: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'grantRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'hasRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'historicalPrices'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, bigint, bigint, bigint, boolean] & {price: bigint, timestamp: bigint, totalSupply: bigint, totalDemand: bigint, exists: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'isOffPeakHour'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'isPeakHour'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'lastUpdateTime'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'maxPrice'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'minPrice'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'minUpdateInterval'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'movingAveragePeriod'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'movingAveragePrice'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'pause'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'paused'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'priceTimestamps'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'pricingSchedule'): TypedContractMethod<
      [],
      [[bigint, bigint, bigint, bigint, bigint, bigint, bigint] & {peakHourMultiplier: bigint, offPeakMultiplier: bigint, standardMultiplier: bigint, peakStartHour: bigint, peakEndHour: bigint, offPeakStartHour: bigint, offPeakEndHour: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'renounceRole'): TypedContractMethod<
      [role: BytesLike, callerConfirmation: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'revokeRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setBasePrice'): TypedContractMethod<
      [newBasePrice: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setExternalPriceFeed'): TypedContractMethod<
      [feedAddress: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setMinUpdateInterval'): TypedContractMethod<
      [intervalInSeconds: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setMovingAveragePeriod'): TypedContractMethod<
      [periodInHours: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setPrice'): TypedContractMethod<
      [newPrice: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setPriceBounds'): TypedContractMethod<
      [_minPrice: BigNumberish, _maxPrice: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setPricingSchedule'): TypedContractMethod<
      [schedule: PriceOracle.PricingScheduleStruct, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setUseExternalFeed'): TypedContractMethod<
      [_useExternal: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'supplyDemandFactor'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'supportsInterface'): TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'unpause'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updatePrice'): TypedContractMethod<
      [totalSupply: BigNumberish, totalDemand: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'useExternalFeed'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;

    getEvent(key: 'BasePriceUpdated'): TypedContractEvent<BasePriceUpdatedEvent.InputTuple, BasePriceUpdatedEvent.OutputTuple, BasePriceUpdatedEvent.OutputObject>;
getEvent(key: 'MovingAverageUpdated'): TypedContractEvent<MovingAverageUpdatedEvent.InputTuple, MovingAverageUpdatedEvent.OutputTuple, MovingAverageUpdatedEvent.OutputObject>;
getEvent(key: 'Paused'): TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
getEvent(key: 'PriceBoundsUpdated'): TypedContractEvent<PriceBoundsUpdatedEvent.InputTuple, PriceBoundsUpdatedEvent.OutputTuple, PriceBoundsUpdatedEvent.OutputObject>;
getEvent(key: 'PriceUpdated'): TypedContractEvent<PriceUpdatedEvent.InputTuple, PriceUpdatedEvent.OutputTuple, PriceUpdatedEvent.OutputObject>;
getEvent(key: 'PriceUpdaterAdded'): TypedContractEvent<PriceUpdaterAddedEvent.InputTuple, PriceUpdaterAddedEvent.OutputTuple, PriceUpdaterAddedEvent.OutputObject>;
getEvent(key: 'PricingScheduleUpdated'): TypedContractEvent<PricingScheduleUpdatedEvent.InputTuple, PricingScheduleUpdatedEvent.OutputTuple, PricingScheduleUpdatedEvent.OutputObject>;
getEvent(key: 'RoleAdminChanged'): TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
getEvent(key: 'RoleGranted'): TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
getEvent(key: 'RoleRevoked'): TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
getEvent(key: 'SupplyDemandUpdated'): TypedContractEvent<SupplyDemandUpdatedEvent.InputTuple, SupplyDemandUpdatedEvent.OutputTuple, SupplyDemandUpdatedEvent.OutputObject>;
getEvent(key: 'Unpaused'): TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;

    filters: {
      
      'BasePriceUpdated(uint256,uint256)': TypedContractEvent<BasePriceUpdatedEvent.InputTuple, BasePriceUpdatedEvent.OutputTuple, BasePriceUpdatedEvent.OutputObject>;
      BasePriceUpdated: TypedContractEvent<BasePriceUpdatedEvent.InputTuple, BasePriceUpdatedEvent.OutputTuple, BasePriceUpdatedEvent.OutputObject>;
    

      'MovingAverageUpdated(uint256)': TypedContractEvent<MovingAverageUpdatedEvent.InputTuple, MovingAverageUpdatedEvent.OutputTuple, MovingAverageUpdatedEvent.OutputObject>;
      MovingAverageUpdated: TypedContractEvent<MovingAverageUpdatedEvent.InputTuple, MovingAverageUpdatedEvent.OutputTuple, MovingAverageUpdatedEvent.OutputObject>;
    

      'Paused(address)': TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
      Paused: TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
    

      'PriceBoundsUpdated(uint256,uint256)': TypedContractEvent<PriceBoundsUpdatedEvent.InputTuple, PriceBoundsUpdatedEvent.OutputTuple, PriceBoundsUpdatedEvent.OutputObject>;
      PriceBoundsUpdated: TypedContractEvent<PriceBoundsUpdatedEvent.InputTuple, PriceBoundsUpdatedEvent.OutputTuple, PriceBoundsUpdatedEvent.OutputObject>;
    

      'PriceUpdated(uint256,uint256,uint256,uint256,uint256)': TypedContractEvent<PriceUpdatedEvent.InputTuple, PriceUpdatedEvent.OutputTuple, PriceUpdatedEvent.OutputObject>;
      PriceUpdated: TypedContractEvent<PriceUpdatedEvent.InputTuple, PriceUpdatedEvent.OutputTuple, PriceUpdatedEvent.OutputObject>;
    

      'PriceUpdaterAdded(address)': TypedContractEvent<PriceUpdaterAddedEvent.InputTuple, PriceUpdaterAddedEvent.OutputTuple, PriceUpdaterAddedEvent.OutputObject>;
      PriceUpdaterAdded: TypedContractEvent<PriceUpdaterAddedEvent.InputTuple, PriceUpdaterAddedEvent.OutputTuple, PriceUpdaterAddedEvent.OutputObject>;
    

      'PricingScheduleUpdated(tuple)': TypedContractEvent<PricingScheduleUpdatedEvent.InputTuple, PricingScheduleUpdatedEvent.OutputTuple, PricingScheduleUpdatedEvent.OutputObject>;
      PricingScheduleUpdated: TypedContractEvent<PricingScheduleUpdatedEvent.InputTuple, PricingScheduleUpdatedEvent.OutputTuple, PricingScheduleUpdatedEvent.OutputObject>;
    

      'RoleAdminChanged(bytes32,bytes32,bytes32)': TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
      RoleAdminChanged: TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
    

      'RoleGranted(bytes32,address,address)': TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
      RoleGranted: TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
    

      'RoleRevoked(bytes32,address,address)': TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
      RoleRevoked: TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
    

      'SupplyDemandUpdated(uint256,uint256)': TypedContractEvent<SupplyDemandUpdatedEvent.InputTuple, SupplyDemandUpdatedEvent.OutputTuple, SupplyDemandUpdatedEvent.OutputObject>;
      SupplyDemandUpdated: TypedContractEvent<SupplyDemandUpdatedEvent.InputTuple, SupplyDemandUpdatedEvent.OutputTuple, SupplyDemandUpdatedEvent.OutputObject>;
    

      'Unpaused(address)': TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
      Unpaused: TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
    
    };
  }