/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface EnergyDataRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "ADMIN_ROLE"
      | "CONVERSION_FACTOR"
      | "DATA_PROVIDER_ROLE"
      | "DEFAULT_ADMIN_ROLE"
      | "addDataProvider"
      | "batchRegisterEnergyData"
      | "batchRegisterUsers"
      | "dataIntervalSeconds"
      | "energyToken"
      | "getAddressFromHouseId"
      | "getAllUsers"
      | "getAvailableSurplus"
      | "getEnergyData"
      | "getRoleAdmin"
      | "getUserCount"
      | "getUserProfile"
      | "grantRole"
      | "hasRole"
      | "houseIdToAddress"
      | "pause"
      | "paused"
      | "reduceSurplus"
      | "registerEnergyData"
      | "registerUser"
      | "registeredUsers"
      | "renounceRole"
      | "revokeRole"
      | "setDataInterval"
      | "supportsInterface"
      | "unpause"
      | "updateEnergyToken"
      | "userEnergyData"
      | "userProfiles"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BatchDataProcessed"
      | "DataIntervalUpdated"
      | "DataProviderAdded"
      | "EnergyDataRegistered"
      | "Paused"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
      | "SurplusCalculated"
      | "TokensMinted"
      | "Unpaused"
      | "UserRegistered"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "CONVERSION_FACTOR",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DATA_PROVIDER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addDataProvider",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "batchRegisterEnergyData",
    values: [AddressLike[], BigNumberish[], BigNumberish[], BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "batchRegisterUsers",
    values: [AddressLike[], string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "dataIntervalSeconds",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "energyToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAddressFromHouseId",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllUsers",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAvailableSurplus",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getEnergyData",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getUserProfile",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "houseIdToAddress",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "reduceSurplus",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "registerEnergyData",
    values: [AddressLike, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "registerUser",
    values: [AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "registeredUsers",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setDataInterval",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "updateEnergyToken",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "userEnergyData",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "userProfiles",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "ADMIN_ROLE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "CONVERSION_FACTOR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DATA_PROVIDER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addDataProvider",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "batchRegisterEnergyData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "batchRegisterUsers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "dataIntervalSeconds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "energyToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAddressFromHouseId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllUsers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAvailableSurplus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEnergyData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserProfile",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "houseIdToAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "reduceSurplus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerEnergyData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerUser",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registeredUsers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setDataInterval",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateEnergyToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userEnergyData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userProfiles",
    data: BytesLike
  ): Result;
}

export namespace BatchDataProcessedEvent {
  export type InputTuple = [userCount: BigNumberish, timestamp: BigNumberish];
  export type OutputTuple = [userCount: bigint, timestamp: bigint];
  export interface OutputObject {
    userCount: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DataIntervalUpdatedEvent {
  export type InputTuple = [newInterval: BigNumberish];
  export type OutputTuple = [newInterval: bigint];
  export interface OutputObject {
    newInterval: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DataProviderAddedEvent {
  export type InputTuple = [provider: AddressLike];
  export type OutputTuple = [provider: string];
  export interface OutputObject {
    provider: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EnergyDataRegisteredEvent {
  export type InputTuple = [
    user: AddressLike,
    consumption: BigNumberish,
    production: BigNumberish,
    surplus: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    consumption: bigint,
    production: bigint,
    surplus: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    user: string;
    consumption: bigint;
    production: bigint;
    surplus: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SurplusCalculatedEvent {
  export type InputTuple = [user: AddressLike, surplusAmount: BigNumberish];
  export type OutputTuple = [user: string, surplusAmount: bigint];
  export interface OutputObject {
    user: string;
    surplusAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokensMintedEvent {
  export type InputTuple = [user: AddressLike, amount: BigNumberish];
  export type OutputTuple = [user: string, amount: bigint];
  export interface OutputObject {
    user: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UserRegisteredEvent {
  export type InputTuple = [user: AddressLike, houseId: string];
  export type OutputTuple = [user: string, houseId: string];
  export interface OutputObject {
    user: string;
    houseId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface EnergyDataRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): EnergyDataRegistry;
  waitForDeployment(): Promise<this>;

  interface: EnergyDataRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  CONVERSION_FACTOR: TypedContractMethod<[], [bigint], "view">;

  DATA_PROVIDER_ROLE: TypedContractMethod<[], [string], "view">;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  addDataProvider: TypedContractMethod<
    [provider: AddressLike],
    [void],
    "nonpayable"
  >;

  batchRegisterEnergyData: TypedContractMethod<
    [
      users: AddressLike[],
      consumptions: BigNumberish[],
      productions: BigNumberish[],
      timestamp: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  batchRegisterUsers: TypedContractMethod<
    [users: AddressLike[], houseIds: string[]],
    [void],
    "nonpayable"
  >;

  dataIntervalSeconds: TypedContractMethod<[], [bigint], "view">;

  energyToken: TypedContractMethod<[], [string], "view">;

  getAddressFromHouseId: TypedContractMethod<
    [houseId: string],
    [string],
    "view"
  >;

  getAllUsers: TypedContractMethod<[], [string[]], "view">;

  getAvailableSurplus: TypedContractMethod<
    [user: AddressLike],
    [bigint],
    "view"
  >;

  getEnergyData: TypedContractMethod<
    [user: AddressLike, timestamp: BigNumberish],
    [
      [bigint, bigint, bigint, bigint] & {
        consumption: bigint;
        production: bigint;
        surplus: bigint;
        recordedTime: bigint;
      }
    ],
    "view"
  >;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  getUserCount: TypedContractMethod<[], [bigint], "view">;

  getUserProfile: TypedContractMethod<
    [user: AddressLike],
    [
      [bigint, bigint, bigint, bigint, bigint, string] & {
        totalConsumption: bigint;
        totalProduction: bigint;
        totalSurplusGenerated: bigint;
        currentSurplus: bigint;
        lastUpdateTime: bigint;
        houseId: string;
      }
    ],
    "view"
  >;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  houseIdToAddress: TypedContractMethod<[arg0: string], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  reduceSurplus: TypedContractMethod<
    [user: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  registerEnergyData: TypedContractMethod<
    [
      user: AddressLike,
      consumption: BigNumberish,
      production: BigNumberish,
      timestamp: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  registerUser: TypedContractMethod<
    [user: AddressLike, houseId: string],
    [void],
    "nonpayable"
  >;

  registeredUsers: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  renounceRole: TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  setDataInterval: TypedContractMethod<
    [newInterval: BigNumberish],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  updateEnergyToken: TypedContractMethod<
    [newTokenAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  userEnergyData: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, boolean] & {
        consumption: bigint;
        production: bigint;
        surplus: bigint;
        timestamp: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;

  userProfiles: TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, bigint, bigint, bigint, bigint, bigint, boolean, string] & {
        userAddress: string;
        totalConsumption: bigint;
        totalProduction: bigint;
        totalSurplusGenerated: bigint;
        currentSurplus: bigint;
        lastUpdateTime: bigint;
        isRegistered: boolean;
        houseId: string;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "CONVERSION_FACTOR"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "DATA_PROVIDER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "addDataProvider"
  ): TypedContractMethod<[provider: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "batchRegisterEnergyData"
  ): TypedContractMethod<
    [
      users: AddressLike[],
      consumptions: BigNumberish[],
      productions: BigNumberish[],
      timestamp: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "batchRegisterUsers"
  ): TypedContractMethod<
    [users: AddressLike[], houseIds: string[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "dataIntervalSeconds"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "energyToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getAddressFromHouseId"
  ): TypedContractMethod<[houseId: string], [string], "view">;
  getFunction(
    nameOrSignature: "getAllUsers"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getAvailableSurplus"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getEnergyData"
  ): TypedContractMethod<
    [user: AddressLike, timestamp: BigNumberish],
    [
      [bigint, bigint, bigint, bigint] & {
        consumption: bigint;
        production: bigint;
        surplus: bigint;
        recordedTime: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getUserCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getUserProfile"
  ): TypedContractMethod<
    [user: AddressLike],
    [
      [bigint, bigint, bigint, bigint, bigint, string] & {
        totalConsumption: bigint;
        totalProduction: bigint;
        totalSurplusGenerated: bigint;
        currentSurplus: bigint;
        lastUpdateTime: bigint;
        houseId: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "houseIdToAddress"
  ): TypedContractMethod<[arg0: string], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "reduceSurplus"
  ): TypedContractMethod<
    [user: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registerEnergyData"
  ): TypedContractMethod<
    [
      user: AddressLike,
      consumption: BigNumberish,
      production: BigNumberish,
      timestamp: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registerUser"
  ): TypedContractMethod<
    [user: AddressLike, houseId: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registeredUsers"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setDataInterval"
  ): TypedContractMethod<[newInterval: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateEnergyToken"
  ): TypedContractMethod<[newTokenAddress: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "userEnergyData"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, boolean] & {
        consumption: bigint;
        production: bigint;
        surplus: bigint;
        timestamp: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "userProfiles"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, bigint, bigint, bigint, bigint, bigint, boolean, string] & {
        userAddress: string;
        totalConsumption: bigint;
        totalProduction: bigint;
        totalSurplusGenerated: bigint;
        currentSurplus: bigint;
        lastUpdateTime: bigint;
        isRegistered: boolean;
        houseId: string;
      }
    ],
    "view"
  >;

  getEvent(
    key: "BatchDataProcessed"
  ): TypedContractEvent<
    BatchDataProcessedEvent.InputTuple,
    BatchDataProcessedEvent.OutputTuple,
    BatchDataProcessedEvent.OutputObject
  >;
  getEvent(
    key: "DataIntervalUpdated"
  ): TypedContractEvent<
    DataIntervalUpdatedEvent.InputTuple,
    DataIntervalUpdatedEvent.OutputTuple,
    DataIntervalUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "DataProviderAdded"
  ): TypedContractEvent<
    DataProviderAddedEvent.InputTuple,
    DataProviderAddedEvent.OutputTuple,
    DataProviderAddedEvent.OutputObject
  >;
  getEvent(
    key: "EnergyDataRegistered"
  ): TypedContractEvent<
    EnergyDataRegisteredEvent.InputTuple,
    EnergyDataRegisteredEvent.OutputTuple,
    EnergyDataRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "SurplusCalculated"
  ): TypedContractEvent<
    SurplusCalculatedEvent.InputTuple,
    SurplusCalculatedEvent.OutputTuple,
    SurplusCalculatedEvent.OutputObject
  >;
  getEvent(
    key: "TokensMinted"
  ): TypedContractEvent<
    TokensMintedEvent.InputTuple,
    TokensMintedEvent.OutputTuple,
    TokensMintedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;
  getEvent(
    key: "UserRegistered"
  ): TypedContractEvent<
    UserRegisteredEvent.InputTuple,
    UserRegisteredEvent.OutputTuple,
    UserRegisteredEvent.OutputObject
  >;

  filters: {
    "BatchDataProcessed(uint256,uint256)": TypedContractEvent<
      BatchDataProcessedEvent.InputTuple,
      BatchDataProcessedEvent.OutputTuple,
      BatchDataProcessedEvent.OutputObject
    >;
    BatchDataProcessed: TypedContractEvent<
      BatchDataProcessedEvent.InputTuple,
      BatchDataProcessedEvent.OutputTuple,
      BatchDataProcessedEvent.OutputObject
    >;

    "DataIntervalUpdated(uint256)": TypedContractEvent<
      DataIntervalUpdatedEvent.InputTuple,
      DataIntervalUpdatedEvent.OutputTuple,
      DataIntervalUpdatedEvent.OutputObject
    >;
    DataIntervalUpdated: TypedContractEvent<
      DataIntervalUpdatedEvent.InputTuple,
      DataIntervalUpdatedEvent.OutputTuple,
      DataIntervalUpdatedEvent.OutputObject
    >;

    "DataProviderAdded(address)": TypedContractEvent<
      DataProviderAddedEvent.InputTuple,
      DataProviderAddedEvent.OutputTuple,
      DataProviderAddedEvent.OutputObject
    >;
    DataProviderAdded: TypedContractEvent<
      DataProviderAddedEvent.InputTuple,
      DataProviderAddedEvent.OutputTuple,
      DataProviderAddedEvent.OutputObject
    >;

    "EnergyDataRegistered(address,uint256,uint256,int256,uint256)": TypedContractEvent<
      EnergyDataRegisteredEvent.InputTuple,
      EnergyDataRegisteredEvent.OutputTuple,
      EnergyDataRegisteredEvent.OutputObject
    >;
    EnergyDataRegistered: TypedContractEvent<
      EnergyDataRegisteredEvent.InputTuple,
      EnergyDataRegisteredEvent.OutputTuple,
      EnergyDataRegisteredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "SurplusCalculated(address,uint256)": TypedContractEvent<
      SurplusCalculatedEvent.InputTuple,
      SurplusCalculatedEvent.OutputTuple,
      SurplusCalculatedEvent.OutputObject
    >;
    SurplusCalculated: TypedContractEvent<
      SurplusCalculatedEvent.InputTuple,
      SurplusCalculatedEvent.OutputTuple,
      SurplusCalculatedEvent.OutputObject
    >;

    "TokensMinted(address,uint256)": TypedContractEvent<
      TokensMintedEvent.InputTuple,
      TokensMintedEvent.OutputTuple,
      TokensMintedEvent.OutputObject
    >;
    TokensMinted: TypedContractEvent<
      TokensMintedEvent.InputTuple,
      TokensMintedEvent.OutputTuple,
      TokensMintedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;

    "UserRegistered(address,string)": TypedContractEvent<
      UserRegisteredEvent.InputTuple,
      UserRegisteredEvent.OutputTuple,
      UserRegisteredEvent.OutputObject
    >;
    UserRegistered: TypedContractEvent<
      UserRegisteredEvent.InputTuple,
      UserRegisteredEvent.OutputTuple,
      UserRegisteredEvent.OutputObject
    >;
  };
}
